version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - backend-network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge
