version: "3.9"
services:
  backend-api:
    image: uncles_be:latest
    # build: ./backend
    depends_on:
      - persistence
    ports:
      - "8000:5555"
    restart: on-failure




  persistence:
    image: mariadb:latest
    ports:
      - "6666:3306"
    volumes:
      - uncles_db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=mainatavihakeri


volumes:
  uncles_db:
    external: true



