version: "3.9"
services:
  backend-api:
    image: python-backend:latest
    # build: ./backend
    depends_on:
      - database
    ports:
      - "8000:5555"
    restart: on-failure
    env_file: .env
    # volumes: ???




  database:
    image: mariadb:latest
    ports:
      - "6666:3306"
    volumes:
      - uncles:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=mainatavihakeri


volumes:
  uncles:
    external: true



